[temperature]
low_range_start = -20.0
low_range_end = 11.0
high_range_start = 14.0
high_range_end = 100.0
ideal_range_start = 11.0
ideal_range_end = 14.0
fridge_cooldown_duration = 300

[humidity]
low_range_start = 0.0
low_range_end = 60.0
high_range_start = 80.0
high_range_end = 100.0
ideal_range_start = 75.0
ideal_range_end = 80.0
humidifier_cooldown_duration = 300
humidifier_activation_duration = 1

[ventilation]
interval = 1800
duration = 60

[influxdb]
host = "http://localhost:8086"
database = "atmosphere_db"

[relay_pins]
humidifier = 14
dehumidifier = 15
ventilator_or_heater = 18
fridge = 17

[webserver]
host = "0.0.0.0"
port = 8080

[sensor_read_cooldown]
duration = 45

[polling_interval]
duration = 60